from circularDoublyLinkedList import *

list = CircularDoublyLinkedList()
list.add(30)
list.printList()
list.add(20)
list.printList()
list.add(10)
list.printList()
list.add(10)
list.printList()
list.add(50)
list.printList()
list.add(40)
list.printList()
list.add(100)
list.printList()
list.add(10)
list.printList()
#a = [4, 3, 3, 2, 1]
#list.extend(a)
#list.reverse()
#list.pop(0)
#print("count(3): ", list.count(3))
#print("get(2): ", list.get(2))
#list.printList()